# Generated by Django 6.0.1 on 2026-01-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('payment_id', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
    ]
